filters:
  - label: ✨ feature
    regexs:
      - /\[(feat|feature)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: 🐛 bug
    regexs:
      - /\[(fix|bug)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: 📝 documentation
    regexs:
      - /\[(docs|doc|documentation)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: 🎨 style
    regexs:
      - /\[(style|styling)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: ♻️ refactor
    regexs:
      - /\[(refactor|refactoring)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: 🧪 test
    regexs:
      - /\[(test|testing)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: 🔧 chore
    regexs:
      - /\[(chore|etc)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: 🔖 release
    regexs:
      - /\[(release)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: ❓ question
    regexs:
      - /\[(question)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: 👷 ci/cd
    regexs:
      - /\[(ci/cd|ci|cd)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
  - label: 🏗️ build
    regexs:
      - /\[(build)\]/i
    events: [ pull_request, issues ]
    targets: [ title ]
