spring:
  config:
    activate:
      on-profile: "docs"

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    groups-order: desc
    operations-sorter: method
    display-request-duration: true
    disable-swagger-default-url: true
  show-actuator: true
  api-docs:
    path: /v3/api-docs
